image: python:3.7-stretch

variables:
  REQUIREMENTS: "requirements.txt"
  REQUIREMENTS2: "requirements2.txt"

stages:
  - test
  - sonar

.test: &test
  stage: test
  before_script:
    - infinity config build-info
    - python --version
    - pip install -U -r $REQUIREMENTS
    - export PYTHONPATH=$(pwd):$PYTHONPATH
  script:
    - flake8 sevenbridges
    - py.test -v --cov-config=setup.cfg
  artifacts:
    paths:
      - coverage_report/*


# Test with python 2.7
test:2.7:
  stage: test
  before_script:
    - infinity config build-info
    - python --version
    - pip install -U -r $REQUIREMENTS2
    - export PYTHONPATH=$(pwd):$PYTHONPATH
  script:
    - flake8 sevenbridges
    - py.test -v --cov=sevenbridges
  image: python:2.7

# Test with python 3.5
test:3.5:
  <<: *test
  image: python:3.5

# Test with python 3.6
test:3.6:
  <<: *test
  image: python:3.6

# Test with python 3.7
test:3.7:
  <<: *test
  image: python:3.7-stretch

sonar:
  stage: sonar
  image: emeraldsquad/sonar-scanner:1.0.0
  script: infinity sonar scanner
  allow_failure: true
  dependencies:
    - test:3.7