language: python

matrix:
  include:
  - python: 2.7
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: 3.8
    dist: bionic
    sudo: true

install:
  - if [[ $TRAVIS_PYTHON_VERSION < 3 ]]; then pip install -r requirements2.txt; else pip install -r requirements.txt; fi

script:
  - flake8 sevenbridges
  - pytest -v --cov-config setup.cfg

before_deploy: echo $TRAVIS_TAG > sevenbridges/VERSION

deploy:
  provider: pypi
  user: sbg
  password:
    secure: THUlIKHYS1OofQ8nZK0vclRBbNkE0vwVr70Jm4WA+9poFrUKip+3CdB5jBIofCRbyHwgxzsHe3DKyUcOiuMIvDh2nKwZahofva/LkiDPhMTMo44k0LL8iYkjJ0KCWvThgpaN89odKaNjPidj6kkJoQ58KBwjfisLNrszfs/VJoqFry/JJ6pE5YcTC+fCrKGzwpDP73yzaHT3Z7vHYRzOsZUWKaqFkcJ3jBkcVBOKoY4Qy98y3XdsZH2I7jkBPv4ySoeMgGIYKWvKRjfH6IFeWyEQOysNVdlG6iqyZmrLq66e/048VX1WgDGLRW+rtbDKKaEcBJJHZclsR5WI9SPmjRIdnTuXL26fhrGU+hibkNqZtW3jBSImm6hGGp3nGax6FF31vXfgGq+xDf5TSRlAlaj3B/0CJFWOUfjnofI9mvhvXJJkzDYhVSzGfMtI6zMrFtDsnmrI7PHiJKWHKBRgLbdE1vvYyPExB9Qbls75nyZhwHQRMdDSJ/Gv6e3BAZEfbkC+5JOErgIrdFfdxtn9TOlY3fzlzWm5oeHidz7sUlu7L+SqquCf7ZWR05R9ozj1EZv1fkNg9vmPTr3vqYnDv9utznxR4H/SZHuePmYqY62TqerQVV8TVHuvlVZFUTHcjGQgu6djoANTc5kLOz4tXLqL2ku8LjP+jzhhzBVC8H4=
  on:
    tags: true
    branch: develop
    python: 3.8
    distributions: sdist bdist_wheel
    repo: sbg/sevenbridges-python
  skip_cleanup: true
